version: '3'

services:
  frontend:
    container_name: gs-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  backend:
    container_name: gs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
      - "9229:9229"
    environment: 
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000
    volumes:
      - ./books:/usr/src/app/books
  elasticsearch:
    container_name: gs-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"

volumes: # Define seperate volume for Elasticsearch data
  esdata: